10 BORDER 1: INK RND * 7
20 PAPER RND * 7
30 PRINT "APRENDE BASIC, VAGO!!! ";
35 REM ** EL PUNTO Y COMA AL FINAL EVITA QUE EN CADA REPETICION EL MENSAJE PRINT INCLUYA UN SALTO DE LINEA **
40 GO TO 10
