10 REM ** PROGRAMA QUE CALCULA UNA TABLA DE MULTIPLICAR **
20 REM ** ELEGIDA POR EL USUARIO **
30 INPUT "QUE TABLA DE MULTIPLICAR QUIERES VER?", n
40 LET m=1
50 PRINT n; " * "; m; " = "; n*m
60 LET m=m+1
70 GO TO 50
